<?php

namespace App\Example\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use App\Core\Repository\AbstractRepository as  AbstractRepository;

class ContractRepository extends AbstractRepository
{
}
