<?php

namespace Siworks\Slim\Doctrine\Example\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Siworks\Slim\Doctrine\Repository\AbstractRepository as  AbstractRepository;

class ContractRepository extends AbstractRepository
{
}
