<?php
/**
 * Created by PhpStorm.
 * User: ng
 * Date: 23/06/17
 * Time: 20:31
 */

namespace App\Example\Model;

use App\Core\Model\AbstractModel;
use Doctrine\ORM\EntityManager;

class AccountModel extends AbstractModel
{

    public function __construct( EntityManager $entityManager)
    {
        $this->repository = $entityManager->getRepository('App\Example\Entity\Account\Account');
        parent::__construct($entityManager);
    }

    public function create(Array $data)
    {
        try{

            if ( ! isset($data['status']) )
            {
                throw new \InvalidArgumentException("Required property 'status' empty or not found (ACCMD0031exc)");
            }

            if ( ! isset($data['token']) )
            {
                throw new \InvalidArgumentException("Required property 'token' empty or not found (ACCMD0032exc)");
            }

            if ( ! isset($data['currency']) )
            {
                throw new \InvalidArgumentException("Required property 'currency' empty or not found (ACCMD0033exc)");
            }

            if ( ! isset($data['paymentDay']) )
            {
                throw new \InvalidArgumentException("Required property 'paymentDay' empty or not found (ACCMD0034exc)");
            }

            $obj = parent::create($data); // TODO: Change the autogenerated stub
            return $obj;
        }
        catch(\InvalidArgumentException $e)
        {
            throw $e;
        }
        catch(\Exception $e)
        {
            throw $e;
        }
    }


    /**
     * @param Object $obj
     * @param Array $data
     * @return mixed
     */
    /**public function populateObject(Array $data)
    {

        if ( isset($data['status']) )
        {
            $obj->setStatus(strtoupper($data['status']));
        }

        if (isset($data['token']))
        {
            $obj->setExtUuid($data['token']);
        }

        if (isset($data['currency']))
        {
            $obj->setCurrency($data['currency']);
        }

        if (isset($data['paymentDay']))
        {
            $obj->setPaymentDay($data['paymentDay']);
        }

        if (isset($data['displayName']) && is_string($data['displayName']))
        {
            $data['displayName'] = filter_var($data['displayName'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW);
            $obj->setDisplayName($data['displayName']);
        }

        parent::populateObject($data);
        //contract create
        //$obj->setContracts()

        //invoice create
        // $obj->setInvoices()->add($invoice);

        return $obj;
    }
     */
}